language: node_js
node_js: "8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
install:
  - 'npm install --ignore-scripts'
  - 'npm install'
  - 'npm run vscode:prepublish'
  - 'npm install -g vsce'
  - 'vsce package'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    sonar-scanner;
    fi
  - 'git stash save'
deploy:
- provider: script
  script: vsce publish -p $VSCODE_TOKEN patch
  skip_cleanup: true
  on:
    repo: camel-tooling/camel-lsp-client-vscode
    branch: master
cache:
  directories:
    - "node_modules"
env: DISPLAY=:99
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master
