version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/camel-lsp-client-vscode
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: test java
          command: java --version
      - run:
          name: Install global npm dependencies
          command: |
            sudo npm install -g typescript vsce
      - run:
          name: npm-ci
          command: npm ci
      - run:
          name: npm-vscode:prepublish
          command: npm run vscode:prepublish
      - run:
          name: vsce-package
          command: vsce package
      # - run:
        #  name: test
         # command: npm test
      - store_artifacts:
          name: Store VS Code logs
          path: /home/circleci/.config/Code/logs
      - run:
          name: test UI
          command: npm run ui-test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - store_artifacts:
          name: Store Camel Language Server log
          path: /tmp/log-camel-lsp.out
      - store_artifacts:
          name: Store VS Code logs of UI test
          path: /home/circleci/camel-lsp-client-vscode/test-resources/settings/logs
      - store_artifacts:
          name: Store Screenshots of UI Tests
          path: /home/circleci/camel-lsp-client-vscode/test-resources/screenshots
