version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: sonarcloud

jobs:
  build:
    working_directory: ~/camel-lsp-client-vscode
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: test java
          command: java --version
      - run:
          name: Install global npm dependencies
          command: |
            npm install --prefix=$HOME/.local -g typescript vsce
      - run:
          name: npm-ci
          command: npm ci --prefix=$HOME/.local
      - run:
          name: npm-vscode:prepublish
          command: npm run vscode:prepublish
      - run:
          name: vsce-package
          command: vsce package
      - run:
          name: test
          command: npm test
      - run:
          name: UI test
          command: npm run ui-test
      - store_artifacts:
          name: Store VS Code logs
          path: /home/circleci/.config/Code/logs
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - store_artifacts:
          name: Store Camel Language Server log
          path: /tmp/log-camel-lsp.out
      - store_artifacts:
          name: Store VS Code logs of UI test
          path: /home/circleci/camel-lsp-client-vscode/test-resources/settings/logs
      - store_artifacts:
          name: Store screenshots
          path: /home/circleci/camel-lsp-client-vscode/test-resources/screenshots
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
